### ISSUE TITLE
Can't open json file in EditSQL

### ISSUE THREAD

**Issue by LSY2017** [sunlab-osu/MISP#2]
When using misp_neil.sh,there is an error
"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)".
I check the file "records_train_nointeract_gold.json" and can't open it,maybe this file cause the problem.How to use this file?

**Comment by LittleYUYU** [comment]
Hi, could you check if you are using Python 3 (I tested with python 3.8) while opening the file? It works well on my side. Thanks!

**Comment by LSY2017** [comment]
> Hi, could you check if you are using Python 3 (I tested with python 3.8) while opening the file? It works well on my side. Thanks!

I used python 3.7 as in gpu-py3.yml and I'm still unable to open it., and I can't open it with notepad either. What's more, the dropbox link for data download in SQLova_model is failed, how to get that data?

**Comment by LittleYUYU** [comment]
I have uploaded a new json file; please check and let us know if it works. The previous one may have been damaged for some reasons. 
Links on SQLova_model have been replaced.
Thanks!

**Comment by LSY2017** [comment]
> I have uploaded a new json file; please check and let us know if it works. The previous one may have been damaged for some reasons.
> Links on SQLova_model have been replaced.
> Thanks!

Thank you so much!
